[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nzk-aphiam"
version = "0.1.0"
description = "Integrated Assessment Model for Air Pollution and Health Impact of Korea's National Decarbonization"
authors = [
  { name = "Yehyun Hong" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.11"
dependencies = [
    "requests",
    "python-dotenv",
    "pandas",
    "numpy",
    "loguru",
]

[tool.flit.module]
name = "nzk_aphiam"

[tool.ruff]
line-length = 99
src = ["src"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["nzk_aphiam"]
force-sort-within-sections = true
