"""Parse KOMIPO's directly supplied 2024--2025 monthly mass workbook."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
from pathlib import Path
from typing import Any

from openpyxl import load_workbook
from openpyxl.worksheet.worksheet import Worksheet
import pandas as pd

EXPECTED_WORKBOOK_SHA256 = "365789f6686b98a86925d56fc48d0cfc5824c49c97bd054c6b0011f2e8aa93d1"
REPORTED_MASS_COLUMNS = [
    "date",
    "source_sheet",
    "source_plant_name",
    "source_unit",
    "source_outlet",
    "source_component_label",
    "generation_orgnm",
    "nox",
    "sox",
    "dust_tsp",
]


@dataclass(frozen=True)
class SheetSpec:
    """Expected layout and generation-boundary mapping for one workbook sheet."""

    plant_name: str
    headers: tuple[str, ...]
    outlet_column: int
    pollutant_columns: dict[str, int]
    outlet_boundaries: dict[str, str]
    unit_column: int | None = None
    outlet_units: dict[str, str | None] | None = None


def _same_boundary(outlets: tuple[str, ...], boundary: str) -> dict[str, str]:
    return dict.fromkeys(outlets, boundary)


BORYEONG_STEAM_OUTLETS = ("3", "4", "5", "6", "15", "16")
BORYEONG_COMBINED_OUTLETS = ("7", "8", "9", "10", "11", "12")
BORYEONG_UNITS = {
    **dict.fromkeys(BORYEONG_STEAM_OUTLETS),
    "7": "1CC",
    "8": "1CC",
    "9": "2CC",
    "10": "2CC",
    "11": "3CC",
    "12": "3CC",
}
INCHON_UNITS = {
    "5": "1CC",
    "6": "1CC",
    "7": "2CC",
    "8": "2CC",
    "11": "3CC",
    "12": "3CC",
}

SHEET_SPECS = {
    "보령": SheetSpec(
        plant_name="한국중부발전㈜보령발전본부",
        headers=("측정일자", "사업장명", "호기", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=4,
        pollutant_columns={"dust_tsp": 5, "sox": 6, "nox": 7},
        outlet_boundaries={
            **_same_boundary(BORYEONG_STEAM_OUTLETS, "보령기력"),
            **_same_boundary(BORYEONG_COMBINED_OUTLETS, "보령복합"),
        },
        unit_column=3,
        outlet_units=BORYEONG_UNITS,
    ),
    "신보령": SheetSpec(
        plant_name="한국중부발전㈜신보령발전본부",
        headers=("측정일자", "사업장명", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=3,
        pollutant_columns={"dust_tsp": 4, "sox": 5, "nox": 6},
        outlet_boundaries=_same_boundary(("1", "2"), "신보령기력"),
    ),
    "서천": SheetSpec(
        plant_name="한국중부발전(주)신서천발전본부",
        headers=("측정일자", "사업장명", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=3,
        pollutant_columns={"dust_tsp": 4, "sox": 5, "nox": 6},
        outlet_boundaries=_same_boundary(("1",), "신서천화력"),
    ),
    "인천": SheetSpec(
        plant_name="한국중부발전㈜ 인천발전본부",
        headers=("측정일자", "사업장명", "호기", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=4,
        pollutant_columns={"dust_tsp": 5, "sox": 6, "nox": 7},
        outlet_boundaries=_same_boundary(tuple(INCHON_UNITS), "인천복합"),
        unit_column=3,
        outlet_units=INCHON_UNITS,
    ),
    "서울": SheetSpec(
        plant_name="한국중부발전㈜서울발전본부",
        headers=("측정일자", "사업장명", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=3,
        pollutant_columns={"dust_tsp": 4, "sox": 5, "nox": 6},
        outlet_boundaries=_same_boundary(("1", "2"), "서울복합"),
    ),
    "세종": SheetSpec(
        plant_name="한국중부발전㈜세종발전본부",
        headers=("측정일자", "사업장명", "배출구", "TSP", "SOx", "NOx"),
        outlet_column=3,
        pollutant_columns={"dust_tsp": 4, "sox": 5, "nox": 6},
        outlet_boundaries=_same_boundary(("1", "2"), "세종천연가스"),
    ),
    "제주": SheetSpec(
        plant_name="한국중부발전㈜제주발전본부",
        headers=(
            "일자",
            "사업장명",
            "배출구",
            "NOx\n배출량\n소계",
            "SOx\n배출량\n소계",
            "TSP\n배출량\n소계",
        ),
        outlet_column=3,
        pollutant_columns={"nox": 4, "sox": 5, "dust_tsp": 6},
        outlet_boundaries={
            **_same_boundary(("2", "3"), "제주기력"),
            **_same_boundary(("4", "5"), "제주내연"),
            **_same_boundary(("6", "7"), "제주복합"),
        },
    ),
}


def workbook_sha256(path: Path) -> str:
    """Return the digest of the workbook bytes without modifying the file."""
    if not path.exists():
        raise FileNotFoundError(
            f"Midland Power's directly supplied mass workbook is missing at {path}. "
            "This file was hand-delivered by the provider and cannot be re-scraped or "
            "regenerated by any make target — see docs/project/data_provenance.md for "
            "how it is tracked and who to contact for a copy."
        )
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_workbook_sha256(path: Path, expected_sha256: str = EXPECTED_WORKBOOK_SHA256) -> None:
    """Reject an edited or substituted provider workbook."""
    observed = workbook_sha256(path)
    if observed != expected_sha256:
        raise ValueError(
            f"Provider workbook checksum mismatch for {path}: "
            f"expected {expected_sha256}, observed {observed}."
        )


def _merged_cell_value(sheet: Worksheet, row: int, column: int) -> Any:
    value = sheet.cell(row, column).value
    if value is not None:
        return value
    for merged_range in sheet.merged_cells.ranges:
        if (
            merged_range.min_row <= row <= merged_range.max_row
            and merged_range.min_col <= column <= merged_range.max_col
        ):
            return sheet.cell(merged_range.min_row, merged_range.min_col).value
    return None


def _normalize_outlet(value: Any, sheet_name: str, row: int) -> str:
    if value is None or isinstance(value, bool):
        raise ValueError(f"{sheet_name} row {row} has an invalid outlet: {value!r}")
    if isinstance(value, (int, float)) and float(value).is_integer():
        return str(int(value))
    outlet = str(value).strip()
    if not outlet:
        raise ValueError(f"{sheet_name} row {row} has a blank outlet.")
    return outlet


def _parse_month(value: Any, sheet_name: str, row: int) -> pd.Timestamp:
    if isinstance(value, pd.Timestamp):
        parsed = value
    else:
        parsed = pd.to_datetime(str(value).strip(), format="%Y-%m", errors="coerce")
    if pd.isna(parsed):
        raise ValueError(f"{sheet_name} row {row} has an invalid YYYY-MM month: {value!r}")
    return pd.Timestamp(parsed).to_period("M").to_timestamp()


def _parse_mass(value: Any, sheet_name: str, row: int, pollutant: str) -> float | pd.NA:
    if value is None or (isinstance(value, str) and not value.strip()):
        return pd.NA
    try:
        parsed = float(value)
    except (TypeError, ValueError) as error:
        raise ValueError(
            f"{sheet_name} row {row} has nonnumeric {pollutant} mass: {value!r}"
        ) from error
    if parsed < 0:
        raise ValueError(f"{sheet_name} row {row} has negative {pollutant} mass: {parsed}")
    return parsed


def _validate_sheet_header(sheet: Worksheet, spec: SheetSpec) -> None:
    observed = tuple(sheet.cell(2, column).value for column in range(1, len(spec.headers) + 1))
    if observed != spec.headers:
        raise ValueError(
            f"Unexpected headers in Midland provider sheet {sheet.title!r}. "
            f"Expected {spec.headers!r}, received {observed!r}."
        )
    unit_label = str(sheet.cell(1, len(spec.headers)).value or "").replace(" ", "")
    if unit_label != "단위:kg":
        raise ValueError(f"Midland provider sheet {sheet.title!r} is not explicitly labeled kg.")


def _parse_sheet(sheet: Worksheet, spec: SheetSpec) -> list[dict[str, Any]]:
    _validate_sheet_header(sheet, spec)
    rows: list[dict[str, Any]] = []
    for row_number in range(3, sheet.max_row + 1):
        values = [
            sheet.cell(row_number, column).value for column in range(1, len(spec.headers) + 1)
        ]
        if all(value is None for value in values):
            continue
        if any(
            sheet.cell(row_number, column).data_type == "f"
            for column in range(1, len(spec.headers) + 1)
        ):
            raise ValueError(
                f"Midland provider sheet {sheet.title!r} row {row_number} contains a formula."
            )

        date = _parse_month(values[0], sheet.title, row_number)
        plant_name = str(values[1] or "").strip()
        if plant_name != spec.plant_name:
            raise ValueError(
                f"{sheet.title} row {row_number} has unexpected plant name {plant_name!r}."
            )
        outlet = _normalize_outlet(
            sheet.cell(row_number, spec.outlet_column).value, sheet.title, row_number
        )
        if outlet not in spec.outlet_boundaries:
            raise ValueError(f"{sheet.title} row {row_number} has unmapped outlet {outlet!r}.")

        source_unit: str | None = None
        if spec.unit_column is not None:
            unit_value = _merged_cell_value(sheet, row_number, spec.unit_column)
            source_unit = str(unit_value).strip() if unit_value is not None else None
            expected_unit = (spec.outlet_units or {}).get(outlet)
            if source_unit != expected_unit:
                raise ValueError(
                    f"{sheet.title} row {row_number} outlet {outlet} has unit "
                    f"{source_unit!r}; expected {expected_unit!r}."
                )

        component_label = f"배출구 {outlet}"
        if source_unit:
            component_label = f"{source_unit} {component_label}"
        record: dict[str, Any] = {
            "date": date,
            "source_sheet": sheet.title,
            "source_plant_name": plant_name,
            "source_unit": source_unit,
            "source_outlet": outlet,
            "source_component_label": component_label,
            "generation_orgnm": spec.outlet_boundaries[outlet],
        }
        for pollutant, column in spec.pollutant_columns.items():
            record[pollutant] = _parse_mass(
                sheet.cell(row_number, column).value,
                sheet.title,
                row_number,
                pollutant,
            )
        rows.append(record)
    return rows


def parse_reported_mass_workbook(path: Path) -> pd.DataFrame:
    """Return stack-month reported mass with documented generation boundaries."""
    workbook = load_workbook(path, read_only=False, data_only=False)
    expected_sheets = list(SHEET_SPECS)
    if workbook.sheetnames != expected_sheets:
        raise ValueError(
            f"Unexpected Midland workbook sheets. Expected {expected_sheets!r}, "
            f"received {workbook.sheetnames!r}."
        )

    records: list[dict[str, Any]] = []
    dates_by_sheet: dict[str, set[pd.Timestamp]] = {}
    for sheet_name, spec in SHEET_SPECS.items():
        sheet_records = _parse_sheet(workbook[sheet_name], spec)
        if not sheet_records:
            raise ValueError(f"Midland provider sheet {sheet_name!r} contains no data rows.")
        records.extend(sheet_records)
        dates_by_sheet[sheet_name] = {record["date"] for record in sheet_records}

    first_dates = dates_by_sheet[expected_sheets[0]]
    inconsistent_dates = {
        sheet_name: sorted(dates)
        for sheet_name, dates in dates_by_sheet.items()
        if dates != first_dates
    }
    if inconsistent_dates:
        raise ValueError(
            f"Midland provider sheets do not have identical monthly coverage: {inconsistent_dates}"
        )

    data = pd.DataFrame(records, columns=REPORTED_MASS_COLUMNS)
    if data.duplicated(["source_sheet", "date", "source_outlet"]).any():
        raise ValueError("Midland provider workbook has duplicate sheet/month/outlet rows.")
    for sheet_name, spec in SHEET_SPECS.items():
        observed = data.loc[data["source_sheet"].eq(sheet_name)].groupby("date")["source_outlet"]
        expected = set(spec.outlet_boundaries)
        bad_months = {
            str(date.date()): sorted(set(outlets) ^ expected)
            for date, outlets in observed
            if set(outlets) != expected
        }
        if bad_months:
            raise ValueError(
                f"Midland provider sheet {sheet_name!r} has incomplete outlet coverage: "
                f"{bad_months}"
            )

    for column in [
        "source_sheet",
        "source_plant_name",
        "source_unit",
        "source_outlet",
        "source_component_label",
        "generation_orgnm",
    ]:
        data[column] = data[column].astype("string")
    for column in ["nox", "sox", "dust_tsp"]:
        data[column] = pd.to_numeric(data[column], errors="coerce").astype("Float64")
    return data.sort_values(["date", "source_sheet", "source_outlet"], ignore_index=True)
